# Use root/example as user/password credentials
version: '3.8'

services:
  db:
    image: polfish/finance-tracker-db
    restart: always
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql

volumes:
    db-config:
    db-data: